### ISSUE TITLE
Request pretrained model for NWPU

### ISSUE THREAD

**Issue by YJ-He** [taohan10200/STEERER#12]
Thanks for your unselfish share of this repo, could you upload the pretrained model for NWPU dataset?

**Comment by taohan10200** [comment]
Thanks, pretrained weight on NWPU can be get from this [Link](https://pjlab-my.sharepoint.cn/:u:/g/personal/hantao_dispatch_pjlab_org_cn/ETu2pnFluOtIozpmfd7ptrUBUvCf2TxUD3_w_aW-9iKX8g?e=DoQNZN).

**Comment by YJ-He** [comment]
@taohan10200 Thank you so much. Have a good day!
