### ISSUE TITLE
Question about the data meaning in test_gt_loc.txt

### ISSUE THREAD

**Issue by YJ-He** [taohan10200/STEERER#13]
Hello, could I ask what does each line of data mean in test_gt_loc.txt? 
![image](https://github.com/taohan10200/STEERER/assets/95644882/4d058876-a67f-4374-9f4c-f79bf229f853)

**Comment by cyn2399** [comment]
hello,do you know how to make test_gt_loc.txt? (I have run the prepare_shhb.py, but the result was wrong.)
#14

**Comment by taohan10200** [comment]
Take the first line as example: 1202 977  446 1801 16 23 3 ............

In each line, the first number is image ID (1202), the next number 977 represents how many people in this image.
Then the flowing numbers can be divided into 5-element tuple,  which is similar to the box annotation in object detection.

[ 446 1801 16 23 3 ] is [left_top_w, left_top_h, box_width, box_height, area_range_id]

**Comment by YJ-He** [comment]
@taohan10200 Thanks for your reply.
