### ISSUE TITLE
About when generating a dataset the test_gt_loc.txt was wrong

### ISSUE THREAD

**Issue by cyn2399** [taohan10200/STEERER#14]
hi! Frist of all, thank you to provide the prepared datasets python script for public.  I want to know why my xy location can not be read in the test_gt_loc.txt.  @taohan10200 
<img width="914" alt="截屏2024-03-04 09 58 00" src="https://github.com/taohan10200/STEERER/assets/135931489/60cd8337-504f-4674-b56c-6e655404e4ba">

**Comment by taohan10200** [comment]
Please see this https://github.com/taohan10200/STEERER/issues/13#issuecomment-1980935778

**Comment by cyn2399** [comment]
> Please see this [#13 (comment)](https://github.com/taohan10200/STEERER/issues/13#issuecomment-1980935778)

thank you so much!!!!!! I have solved this problem yesterday. 🩵🩵
