### ISSUE TITLE
Location of pretrained HRNet loaded during training

### ISSUE THREAD

**Issue by LouisThygesen** [taohan10200/STEERER#15]
Could you direct me to the exact pretrained weights used as initialization of HRNet during training on the QNRF dataset ("PretrainedModels/hrnetv2_w48_imagenet_pretrained.pth")? These weights are not saved along with your STEERER weights in OneDrive, and it is not clear to me if the weights I need can be downloaded from https://github.com/HRNet/HRNet-Semantic-Segmentation.

**Comment by taohan10200** [comment]
Sorry for the late reply, you can now download it at: [PretrainedModels Fold](https://pjlab-my.sharepoint.cn/:u:/g/personal/hantao_dispatch_pjlab_org_cn/EcmYmvLT-7hFpMS3t_QhFj0B5eHKOHhSnWrzpRgx3nYtTg?e=3enN4X).

**Comment by LouisThygesen** [comment]
Thank you :-) Keep up the good work!
