### ISSUE TITLE
Requires CUDA?

### ISSUE THREAD

**Issue by alana314** [taohan10200/STEERER#2]
Does this library require CUDA? I'm trying to run on an M2.
```
PackagesNotFoundError: The following packages are not available from current channels:
cudatoolkit=11.3
 ```
  
Thanks

**Comment by taohan10200** [comment]
It is not necessary to run the model on a GPU device. You can only run it on the CPU device.  Can you share the full log so that we can further locate what errors you meet?

**Comment by alana314** [comment]
Thanks for your quick response. I was able to get M2 compatible pytorch and other libraries by removing the version numbers.  
Are there any docs on getting this running? I don't have access to the paper. When I try python cam.py, after fixing a couple path issues, I'm getting this error:  
ImportError: cannot import name 'testval' from 'lib.core.cc_function'

**Comment by taohan10200** [comment]
The cam.py is not the test script, you need to run the python test_loc.py or test_cc.py for inference.
