### ISSUE TITLE
More datasets

### ISSUE THREAD

**Issue by cspk17** [taohan10200/STEERER#4]
STEERER uses the processed datasets (not the original format).
Now, only the processed datasets of SHHB and TRANSCOS_v3 can be downloaded.
Can you share more processed datasets??
Thank you!!

**Comment by taohan10200** [comment]
All processed datasets will be collated and uploaded, please stay tuned!

**Comment by taohan10200** [comment]
All processed datasets are available at: https://pjlab-my.sharepoint.cn/:f:/g/personal/hantao_dispatch_pjlab_org_cn/EpdTPZDeIhxCpR5gr46iXyYBvEC1xo8qX96FvK8geMJs6Q?e=SGfrSS

**Comment by cspk17** [comment]
Hi~ @taohan10200.
When will the NWPU processed dataset be available??
