### ISSUE TITLE
Why does TRANCOS dataset needs to be preprocessed?

### ISSUE THREAD

**Issue by sullivantee** [taohan10200/STEERER#8]
Dear author @taohan10200,  
I downloaded TRANCOS, SHHA, SHHB, and URBAN_TREE, 
but it seems that only TRANCOS is preprocessed (cutting the edges off, etc.), is there a particular reason for that? 
Thanks in advance!!

**Comment by taohan10200** [comment]
Hi, @sullivantee 

TRANCOS is not fully annotated, which was only annotated in some interested regions.  So we cut the edges with the methods proposed in the original paper. The pre-processing guaranteed all cars having labels.
