### ISSUE TITLE
Errors will be reported when training with 2 Gpus. May I ask how to solve this problem

### ISSUE THREAD

**Issue by cyn2399** [taohan10200/STEERER#9]
bash ./train.sh configs/SHHB_final.py 7,8
<img width="1160" alt="截屏2023-11-23 22 50 21" src="https://github.com/taohan10200/STEERER/assets/135931489/c0e2ab89-958c-492f-a5dc-1d57e31ad5da">

**Comment by cyn2399** [comment]
I have changed the cfg but it didn't  work

**Comment by cyn2399** [comment]
@taohan10200

**Comment by taohan10200** [comment]
Hi, I have found this is raised by the `torchrun`. Please comment the ` torchrun` command and use `torch.distributed.launch`. Update the `train.sh` as following:
```
# !/usr/bin/env sh
# ${GPUS:-4}
set -x


CONFIG=$1
GPUS_ID=${2:-0}    #the default gpu_id is 0 
PORT=${3:-29000}   #the default gpu_id is 1
NNODES=${NNODES:-1}
NODE_RANK=${NODE_RANK:-0}

MASTER_ADDR=${MASTER_ADDR:-"127.0.0.1"}

GPU_NUM=0

for ((i=0; i<${#GPUS_ID}; i++)); do
    if [[ ${GPUS_ID:i:1} =~ [0-9] ]]; then
        ((GPU_NUM++))
    fi
done

source ~/anaconda3/bin/activate STEERER

echo "export CUDA_VISIBLE_DEVICES=$GPUS_ID"
export CUDA_VISIBLE_DEVICES=${GPUS_ID:-"0"}


# torchrun --nproc_per_node=${GPU_NUM} --master_port ${PORT} tools/train_cc.py --cfg ${CONFIG} 

python -m torch.distributed.launch \
    --node_rank=$NODE_RANK \
    --master_addr=$MASTER_ADDR \
    --nproc_per_node=$GPU_NUM \
    --master_port=$PORT \
    tools/train_cc.py --cfg=$CONFIG --launcher="pytorch"
```

By run `sh train.sh configs/SHHB_final.py 1,2  `. My log is:
```
base) [hantao.dispatch@SH-IDC1-10-140-24-18 STEERER]$ sh train.sh configs/SHHB_final.py 1,2
export CUDA_VISIBLE_DEVICES=1,2
/mnt/petrelfs/hantao.dispatch/anaconda3/envs/STEERER/lib/python3.9/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See
https://pytorch.org/docs/stable/distributed.html#launch-utility for
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
=> creating exp/SHHB/MocHRBackbone_hrnet48/SHHB_final_2023-11-24-10-53
=> creating exp/SHHB/MocHRBackbone_hrnet48/SHHB_final_2023-11-24-10-53
GPU idx:1,2
GPU idx:1,2
Added key: store_based_barrier_key:1 to store for rank: 0
Added key: store_based_barrier_key:1 to store for rank: 1
Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 2 nodes.
Rank 1: Completed store-based barrier for key:store_based_barrier_key:1 with 2 nodes.
=> init weights from normal distribution
=> init weights from normal distribution
=> loading pretrained model ../PretrainedModels/hrnetv2_w48_imagenet_pretrained.pth
=> loading pretrained model ../PretrainedModels/hrnetv2_w48_imagenet_pretrained.pth
Missing keys: []
Missing keys: []
Namespace(cfg='configs/SHHB_final.py', local_rank=0, opts=[], launcher='pytorch', debug=False, cfg_options=None)
Config (path: configs/SHHB_final.py): {'gpus': (0, 1), 'log_dir': 'exp', 'workers': 6, 'print_freq': 30, 'seed': 3035, 'network': {'backbone': 'MocHRBackbone', 'sub_arch': 'hrnet48', 'counter_type': 'withMOE', 'resolution_num': [0, 1, 2, 3], 'loss_weight': [1.0, 0.5, 0.25, 0.125], 'sigma': [4], 'gau_kernel_size': 15, 'baseline_loss': False, 'pretrained_backbone': '../PretrainedModels/hrnetv2_w48_imagenet_pretrained.pth', 'head': {'type': 'CountingHead', 'fuse_method': 'cat', 'in_channels': 96, 'stages_channel': [384, 192, 96, 48], 'inter_layer': [64, 32, 16], 'out_channels': 1}}, 'dataset': {'name': 'SHHB','root': '../ProcessedData/SHHB/', 'test_set': 'test.txt', 'train_set': 'train.txt', 'loc_gt': 'test_gt_loc.txt', 'num_classes': 4, 'den_factor': 100, 'extra_train_set': None}, 'optimizer': {'NAME': 'adamw', 'BASE_LR': 1e-05, 'BETAS': (0.9, 0.999), 'WEIGHT_DECAY': 0.01, 'EPS': 1e-08, 'MOMENTUM': 0.9, 'AMSGRAD': False, 'NESTEROV': True}, 'lr_config': {'NAME': 'cosine', 'WARMUP_METHOD': 'linear', 'DECAY_EPOCHS': 250, 'DECAY_RATE': 0.1, 'WARMUP_EPOCHS': 10, 'WARMUP_LR': 5e-07, 'MIN_LR': 1e-07}, 'log_config': {'interval': 50, 'hooks': [{'type': 'TextLoggerHook'}]}, 'train': {'counter': 'normal', 'image_size': (768, 768), 'route_size': (256, 256), 'base_size': 2048, 'batch_size_per_gpu': 8, 'shuffle': True, 'begin_epoch': 0, 'end_epoch': 300, 'extra_epoch': 0, 'extra_lr': 0, 'resume_path': None, 'flip': True, 'multi_scale': True, 'scale_factor': (0.5, 2.0), 'val_span': [-1000, -600, -400, -200, -200, -100, -100], 'downsamplerate': 1, 'ignore_label': 255}, 'test': {'image_size': (1024, 2048), 'base_size': 2048, 'loc_base_size': 2048, 'loc_threshold': 0.2, 'batch_size_per_gpu': 1, 'patch_batch_size': 16, 'flip_test': False, 'multi_scale': False, 'model_file': ''}, 'CUDNN': {'BENCHMARK': True, 'DETERMINISTIC': False, 'ENABLED': True}}
| name                               | #elements or shape   |
|:-----------------------------------|:---------------------|
| model                              | 64.6M                |
|  backbone                          |  63.6M               |
|   backbone.conv1                   |   1.7K               |
|    backbone.conv1.weight           |    (64, 3, 3, 3)     |
|   backbone.bn1                     |   0.1K               |
|    backbone.bn1.weight             |    (64,)             |
|    backbone.bn1.bias               |    (64,)             |
|   backbone.conv2                   |   36.9K              |
|    backbone.conv2.weight           |    (64, 64, 3, 3)    |
|   backbone.bn2                     |   0.1K               |
|    backbone.bn2.weight             |    (64,)             |
|    backbone.bn2.bias               |    (64,)             |
|   backbone.layer1                  |   0.3M               |
|    backbone.layer1.0               |    75.0K             |
|    backbone.layer1.1               |    70.4K             |
|    backbone.layer1.2               |    70.4K             |
|    backbone.layer1.3               |    70.4K             |
|   backbone.transition1             |   0.3M               |
|    backbone.transition1.0          |    0.1M              |
|    backbone.transition1.1          |    0.2M              |
|   backbone.stage2                  |   0.9M               |
|    backbone.stage2.0               |    0.9M              |
|   backbone.transition2             |   0.2M               |
|    backbone.transition2.2          |    0.2M              |
|   backbone.stage3                  |   15.3M              |
|    backbone.stage3.0               |    3.8M              |
|    backbone.stage3.1               |    3.8M              |
|    backbone.stage3.2               |    3.8M              |
|    backbone.stage3.3               |    3.8M              |
|   backbone.transition3             |   0.7M               |
|    backbone.transition3.3          |    0.7M              |
|   backbone.stage4                  |   45.9M              |
|    backbone.stage4.0               |    15.9M             |
|    backbone.stage4.1               |    15.9M             |
|    backbone.stage4.2               |    14.1M             |
|  gaussian                          |  0.2K                |
|   gaussian.gaussian                |   0.2K               |
|    gaussian.gaussian.gkernel       |    0.2K              |
|  multi_counters                    |  78.6K               |
|   multi_counters.decoder           |   78.6K              |
|    multi_counters.decoder.1        |    55.3K             |
|    multi_counters.decoder.2        |    0.1K              |
|    multi_counters.decoder.4        |    18.4K             |
|    multi_counters.decoder.5        |    64                |
|    multi_counters.decoder.8        |    4.6K              |
|    multi_counters.decoder.9        |    32                |
|    multi_counters.decoder.11       |    16                |
|  counter_copy                      |  78.6K               |
|   counter_copy.decoder             |   78.6K              |
|    counter_copy.decoder.1          |    55.3K             |
|    counter_copy.decoder.2          |    0.1K              |
|    counter_copy.decoder.4          |    18.4K             |
|    counter_copy.decoder.5          |    64                |
|    counter_copy.decoder.8          |    4.6K              |
|    counter_copy.decoder.9          |    32                |
|    counter_copy.decoder.11         |    16                |
|  upsample_module                   |  0.9M                |
|   upsample_module.multi_outputs    |   0.9M               |
|    upsample_module.multi_outputs.0 |    37.1K             |
|    upsample_module.multi_outputs.1 |    0.3M              |
|    upsample_module.multi_outputs.2 |    0.3M              |
|    upsample_module.multi_outputs.3 |    0.3M              |
```

**Comment by cyn2399** [comment]
> Hi, I have found this is raised by the `torchrun`. Please comment the ` torchrun` command and use `torch.distributed.launch`. Update the `train.sh` as following:
> 
> ```
> # !/usr/bin/env sh
> # ${GPUS:-4}
> set -x
> 
> 
> CONFIG=$1
> GPUS_ID=${2:-0}    #the default gpu_id is 0 
> PORT=${3:-29000}   #the default gpu_id is 1
> NNODES=${NNODES:-1}
> NODE_RANK=${NODE_RANK:-0}
> 
> MASTER_ADDR=${MASTER_ADDR:-"127.0.0.1"}
> 
> GPU_NUM=0
> 
> for ((i=0; i<${#GPUS_ID}; i++)); do
>     if [[ ${GPUS_ID:i:1} =~ [0-9] ]]; then
>         ((GPU_NUM++))
>     fi
> done
> 
> source ~/anaconda3/bin/activate STEERER
> 
> echo "export CUDA_VISIBLE_DEVICES=$GPUS_ID"
> export CUDA_VISIBLE_DEVICES=${GPUS_ID:-"0"}
> 
> 
> # torchrun --nproc_per_node=${GPU_NUM} --master_port ${PORT} tools/train_cc.py --cfg ${CONFIG} 
> 
> python -m torch.distributed.launch \
>     --node_rank=$NODE_RANK \
>     --master_addr=$MASTER_ADDR \
>     --nproc_per_node=$GPU_NUM \
>     --master_port=$PORT \
>     tools/train_cc.py --cfg=$CONFIG --launcher="pytorch"
> ```
> 
> By run `sh train.sh configs/SHHB_final.py 1,2 `. My log is:
> 
> ```
> base) [hantao.dispatch@SH-IDC1-10-140-24-18 STEERER]$ sh train.sh configs/SHHB_final.py 1,2
> export CUDA_VISIBLE_DEVICES=1,2
> /mnt/petrelfs/hantao.dispatch/anaconda3/envs/STEERER/lib/python3.9/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
> and will be removed in future. Use torchrun.
> Note that --use_env is set by default in torchrun.
> If your script expects `--local_rank` argument to be set, please
> change it to read from `os.environ['LOCAL_RANK']` instead. See
> https://pytorch.org/docs/stable/distributed.html#launch-utility for
> further instructions
> 
>   warnings.warn(
> WARNING:torch.distributed.run:
> *****************************************
> Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
> *****************************************
> => creating exp/SHHB/MocHRBackbone_hrnet48/SHHB_final_2023-11-24-10-53
> => creating exp/SHHB/MocHRBackbone_hrnet48/SHHB_final_2023-11-24-10-53
> GPU idx:1,2
> GPU idx:1,2
> Added key: store_based_barrier_key:1 to store for rank: 0
> Added key: store_based_barrier_key:1 to store for rank: 1
> Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 2 nodes.
> Rank 1: Completed store-based barrier for key:store_based_barrier_key:1 with 2 nodes.
> => init weights from normal distribution
> => init weights from normal distribution
> => loading pretrained model ../PretrainedModels/hrnetv2_w48_imagenet_pretrained.pth
> => loading pretrained model ../PretrainedModels/hrnetv2_w48_imagenet_pretrained.pth
> Missing keys: []
> Missing keys: []
> Namespace(cfg='configs/SHHB_final.py', local_rank=0, opts=[], launcher='pytorch', debug=False, cfg_options=None)
> Config (path: configs/SHHB_final.py): {'gpus': (0, 1), 'log_dir': 'exp', 'workers': 6, 'print_freq': 30, 'seed': 3035, 'network': {'backbone': 'MocHRBackbone', 'sub_arch': 'hrnet48', 'counter_type': 'withMOE', 'resolution_num': [0, 1, 2, 3], 'loss_weight': [1.0, 0.5, 0.25, 0.125], 'sigma': [4], 'gau_kernel_size': 15, 'baseline_loss': False, 'pretrained_backbone': '../PretrainedModels/hrnetv2_w48_imagenet_pretrained.pth', 'head': {'type': 'CountingHead', 'fuse_method': 'cat', 'in_channels': 96, 'stages_channel': [384, 192, 96, 48], 'inter_layer': [64, 32, 16], 'out_channels': 1}}, 'dataset': {'name': 'SHHB','root': '../ProcessedData/SHHB/', 'test_set': 'test.txt', 'train_set': 'train.txt', 'loc_gt': 'test_gt_loc.txt', 'num_classes': 4, 'den_factor': 100, 'extra_train_set': None}, 'optimizer': {'NAME': 'adamw', 'BASE_LR': 1e-05, 'BETAS': (0.9, 0.999), 'WEIGHT_DECAY': 0.01, 'EPS': 1e-08, 'MOMENTUM': 0.9, 'AMSGRAD': False, 'NESTEROV': True}, 'lr_config': {'NAME': 'cosine', 'WARMUP_METHOD': 'linear', 'DECAY_EPOCHS': 250, 'DECAY_RATE': 0.1, 'WARMUP_EPOCHS': 10, 'WARMUP_LR': 5e-07, 'MIN_LR': 1e-07}, 'log_config': {'interval': 50, 'hooks': [{'type': 'TextLoggerHook'}]}, 'train': {'counter': 'normal', 'image_size': (768, 768), 'route_size': (256, 256), 'base_size': 2048, 'batch_size_per_gpu': 8, 'shuffle': True, 'begin_epoch': 0, 'end_epoch': 300, 'extra_epoch': 0, 'extra_lr': 0, 'resume_path': None, 'flip': True, 'multi_scale': True, 'scale_factor': (0.5, 2.0), 'val_span': [-1000, -600, -400, -200, -200, -100, -100], 'downsamplerate': 1, 'ignore_label': 255}, 'test': {'image_size': (1024, 2048), 'base_size': 2048, 'loc_base_size': 2048, 'loc_threshold': 0.2, 'batch_size_per_gpu': 1, 'patch_batch_size': 16, 'flip_test': False, 'multi_scale': False, 'model_file': ''}, 'CUDNN': {'BENCHMARK': True, 'DETERMINISTIC': False, 'ENABLED': True}}
> | name                               | #elements or shape   |
> |:-----------------------------------|:---------------------|
> | model                              | 64.6M                |
> |  backbone                          |  63.6M               |
> |   backbone.conv1                   |   1.7K               |
> |    backbone.conv1.weight           |    (64, 3, 3, 3)     |
> |   backbone.bn1                     |   0.1K               |
> |    backbone.bn1.weight             |    (64,)             |
> |    backbone.bn1.bias               |    (64,)             |
> |   backbone.conv2                   |   36.9K              |
> |    backbone.conv2.weight           |    (64, 64, 3, 3)    |
> |   backbone.bn2                     |   0.1K               |
> |    backbone.bn2.weight             |    (64,)             |
> |    backbone.bn2.bias               |    (64,)             |
> |   backbone.layer1                  |   0.3M               |
> |    backbone.layer1.0               |    75.0K             |
> |    backbone.layer1.1               |    70.4K             |
> |    backbone.layer1.2               |    70.4K             |
> |    backbone.layer1.3               |    70.4K             |
> |   backbone.transition1             |   0.3M               |
> |    backbone.transition1.0          |    0.1M              |
> |    backbone.transition1.1          |    0.2M              |
> |   backbone.stage2                  |   0.9M               |
> |    backbone.stage2.0               |    0.9M              |
> |   backbone.transition2             |   0.2M               |
> |    backbone.transition2.2          |    0.2M              |
> |   backbone.stage3                  |   15.3M              |
> |    backbone.stage3.0               |    3.8M              |
> |    backbone.stage3.1               |    3.8M              |
> |    backbone.stage3.2               |    3.8M              |
> |    backbone.stage3.3               |    3.8M              |
> |   backbone.transition3             |   0.7M               |
> |    backbone.transition3.3          |    0.7M              |
> |   backbone.stage4                  |   45.9M              |
> |    backbone.stage4.0               |    15.9M             |
> |    backbone.stage4.1               |    15.9M             |
> |    backbone.stage4.2               |    14.1M             |
> |  gaussian                          |  0.2K                |
> |   gaussian.gaussian                |   0.2K               |
> |    gaussian.gaussian.gkernel       |    0.2K              |
> |  multi_counters                    |  78.6K               |
> |   multi_counters.decoder           |   78.6K              |
> |    multi_counters.decoder.1        |    55.3K             |
> |    multi_counters.decoder.2        |    0.1K              |
> |    multi_counters.decoder.4        |    18.4K             |
> |    multi_counters.decoder.5        |    64                |
> |    multi_counters.decoder.8        |    4.6K              |
> |    multi_counters.decoder.9        |    32                |
> |    multi_counters.decoder.11       |    16                |
> |  counter_copy                      |  78.6K               |
> |   counter_copy.decoder             |   78.6K              |
> |    counter_copy.decoder.1          |    55.3K             |
> |    counter_copy.decoder.2          |    0.1K              |
> |    counter_copy.decoder.4          |    18.4K             |
> |    counter_copy.decoder.5          |    64                |
> |    counter_copy.decoder.8          |    4.6K              |
> |    counter_copy.decoder.9          |    32                |
> |    counter_copy.decoder.11         |    16                |
> |  upsample_module                   |  0.9M                |
> |   upsample_module.multi_outputs    |   0.9M               |
> |    upsample_module.multi_outputs.0 |    37.1K             |
> |    upsample_module.multi_outputs.1 |    0.3M              |
> |    upsample_module.multi_outputs.2 |    0.3M              |
> |    upsample_module.multi_outputs.3 |    0.3M              |
> ```

**Comment by cyn2399** [comment]
Thank you so much!!!!! its work! ❤️ @taohan10200
